title: Greg Westphal
description: Personal Blog for Greg

url: https://github.com/gtw2
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Resume
   url: /westphal_resume.pdf
 - title: Contact
   url: /contact

social:
   github: gtw2
   email: gtw2@illinois.com
